# Generated by Django 4.1 on 2022-08-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipesapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(null=True, upload_to="recipesapp/images/"),
        ),
    ]
